# Generated by Django 5.0.2 on 2024-02-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image_url',
            field=models.URLField(default='https://www.tien21.es/blog/wp-content/uploads/2022/05/sin-senal-2.jpg'),
        ),
    ]
