# Generated by Django 5.0.2 on 2024-02-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
